### ISSUE TITLE
code for that uses both user image and controlnet?

### ISSUE THREAD

**Issue by LDYang694** [naver-ai/StyleKeeper#10]
Thank you for your excellent work. I wonder there  is any code that uses both user image and controlnet?

**Comment by taki0112** [comment]
Here is the code
* [user image](https://github.com/naver-ai/Visual-Style-Prompting/blob/1a22e7a2b7106b7093d6c1b557441335a78105ff/vsp_real_script.py)
* [controlnet w/ depth](https://github.com/naver-ai/Visual-Style-Prompting/blob/1a22e7a2b7106b7093d6c1b557441335a78105ff/vsp_control-depth_script.py)
* [controlnet w/ edge](https://github.com/naver-ai/Visual-Style-Prompting/blob/1a22e7a2b7106b7093d6c1b557441335a78105ff/vsp_control-edge_script.py)
