### ISSUE TITLE
Demo is Unavailable

### ISSUE THREAD

**Issue by Mactor2018** [naver-ai/StyleKeeper#11]
Hello @taki0112, thanks for your work! I'm very interested about your VisualStylePrompting, but the demo on Huggingface is currently unavailable to access.

**Comment by ewebgh33** [comment]
Did this ever get any further development?
Also yes, the demo is down.
Obsolete? What took the place of this, if so?
If not obsolete... I wonder why I have not heard anything about this for many months. Seems it would be superior to describing style in words, if we can just feed it an image?

**Comment by taki0112** [comment]
Apologies for the late response. To run the demo, I need GPU support, but the support period has ended. Unfortunately, it seems I can no longer use the demo and will have to proceed locally with [the following code](https://github.com/naver-ai/Visual-Style-Prompting/blob/1a22e7a2b7106b7093d6c1b557441335a78105ff/vsp_real_script.py). I apologize for the inconvenience.
