### ISSUE TITLE
where is "scale" image?

### ISSUE THREAD

**Issue by NJUSTzandyz** [naver-ai/StyleKeeper#2]
Hello! I am very interested in the operation of visualize_attention in this article. However, when I tried to run visualize_attn_map_script, I noticed that line 49 requires reading the file named attn_map_paired_rgb_grid_name = f"{style_name}_src_{src_name}_tgt_{tgt_name}_scale_1.0_activate_layer_(0, 0)(108, 140)_seed_{seed}.png". It seems that no image with a scale has been generated before. Could you please tell me how this image is generated?

Additionally, I found that the files visualize_attn_map_script.py and save_attn_map_script.py seem to need to be moved to the main directory for smoother operation.

**Comment by taki0112** [comment]
This value is not considered by the current code.
