### ISSUE TITLE
How does Conv2d transform style images into embedding vectors that can be added to self-attention

### ISSUE THREAD

**Issue by codemakerzz** [naver-ai/StyleKeeper#9]
How does Conv2d transform style images into embedding vectors that can be added to self-attention， I want to see where the code is located

**Comment by zimenglan-sysu-512** [comment]
+1

**Comment by gph1q** [comment]
Is it solved?

**Comment by taki0112** [comment]
Through DDIM inversion, the style image is converted into a latent representation. Afterward, through [the following code](https://github.com/naver-ai/Visual-Style-Prompting/blob/1a22e7a2b7106b7093d6c1b557441335a78105ff/pipelines/inverted_ve_pipeline.py#L433), the style is applied by swapping in the self-attention layer.
